In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

In [4]:
df = pd.read_csv("../raw/CrisisLexRec.txt", sep="\t", engine="python")

In [16]:
df.head(30)

         crisis_names
0        flood crisis
1             victims
2       flood victims
3      flood powerful
4     powerful storms
5       hoisted flood
6      storms amazing
7           explosion
8      amazing rescue
9        rescue women
10         flood cost
11       counts flood
12         toll rises
13       braces river
14        river peaks
15     crisis deepens
16            prayers
17   thoughts prayers
18   affected tornado
19           affected
20         death toll
21     tornado relief
22       photos flood
23        water rises
24               toll
25       flood waters
26       flood appeal
27  victims explosion
28    bombing suspect
29  massive explosion

In [6]:
df[df.duplicated()]

Empty DataFrame
Columns: [crisis_names]
Index: []

In [7]:
sorted_df = df.sort_values(by="crisis_names",ascending = True)

In [8]:
sorted_df.head()

            crisis_names
158  accepting financial
19              affected
30        affected areas
109   affected explosion
60     affected flooding

In [9]:
sorted_df.shape

(379, 1)

In [20]:
from collections import Counter

all_words = []

for sentence in sorted_df["crisis_names"]:
    words = sentence.lower().split()
    all_words.extend(words)

word_freq = Counter(all_words)

common_words = word_freq.most_common(70)

print(common_words)

[('flood', 44), ('explosion', 28), ('hurricane', 21), ('tornado', 16), ('victims', 14), ('dead', 13), ('prayers', 12), ('affected', 10), ('help', 10), ('people', 9), ('bombing', 9), ('suspect', 9), ('injured', 8), ('crisis', 7), ('praying', 7), ('killed', 7), ('relief', 6), ('donate', 6), ('rescue', 5), ('floods', 5), ('fire', 5), ('reported', 5), ('police', 5), ('massive', 5), ('redcross', 5), ('breaking', 4), ('death', 4), ('toll', 4), ('disaster', 4), ('video', 4), ('waters', 4), ('saddened', 3), ('braces', 3), ('major', 3), ('river', 3), ('enforcement', 3), ('deaths', 3), ('rises', 3), ('worsens', 3), ('damage', 3), ('hundreds', 3), ('missing', 3), ('torrential', 3), ('deadly', 3), ('died', 3), ('explosions', 3), ('donated', 3), ('donation', 3), ('responders', 3), ('heart', 3), ('rebuilt', 3), ('text', 3), ('homes', 3), ('lives', 3), ('lost', 3), ('toxins', 3), ('survivor', 3), ('financial', 2), ('flooding', 2), ('alive', 2), ('rubble', 2), ('amazing', 2), ('appeal', 2), ('arrest', 2), ('assist', 2), ('attack', 2), ('investigation', 2), ('shot', 2), ('bombings', 2), ('news', 2)]