In [51]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import os

In [52]:
df = pd.read_csv("../raw/CrisisLexRec.txt", sep="\t", engine="python")

In [53]:
df.head(30)

         crisis_names
0        flood crisis
1             victims
2       flood victims
3      flood powerful
4     powerful storms
5       hoisted flood
6      storms amazing
7           explosion
8      amazing rescue
9        rescue women
10         flood cost
11       counts flood
12         toll rises
13       braces river
14        river peaks
15     crisis deepens
16            prayers
17   thoughts prayers
18   affected tornado
19           affected
20         death toll
21     tornado relief
22       photos flood
23        water rises
24               toll
25       flood waters
26       flood appeal
27  victims explosion
28    bombing suspect
29  massive explosion

In [54]:
df[df.duplicated()]

Empty DataFrame
Columns: [crisis_names]
Index: []

In [55]:
sorted_df = df.sort_values(by="crisis_names",ascending = True)

In [56]:
sorted_df.head()

            crisis_names
158  accepting financial
19              affected
30        affected areas
109   affected explosion
60     affected flooding

In [57]:
sorted_df[sorted_df['crisis_names'] == "prayers"]

   crisis_names
16      prayers

In [58]:
sorted_df[sorted_df['crisis_names'] == "explosion"]

  crisis_names
7    explosion

In [59]:
sorted_df.shape

(379, 1)

Empty DataFrame
Columns: [crisis_names]
Index: []

In [60]:
from collections import Counter

all_words = []

for sentence in sorted_df["crisis_names"]:
    words = sentence.lower().split()
    all_words.extend(words)

word_freq = Counter(all_words)

common_words = word_freq.most_common(70)

print(common_words)

[('flood', 44), ('explosion', 28), ('hurricane', 21), ('tornado', 16), ('victims', 14), ('dead', 13), ('prayers', 12), ('affected', 10), ('help', 10), ('people', 9), ('bombing', 9), ('suspect', 9), ('injured', 8), ('crisis', 7), ('praying', 7), ('killed', 7), ('relief', 6), ('donate', 6), ('rescue', 5), ('floods', 5), ('fire', 5), ('reported', 5), ('police', 5), ('massive', 5), ('redcross', 5), ('breaking', 4), ('death', 4), ('toll', 4), ('disaster', 4), ('video', 4), ('waters', 4), ('saddened', 3), ('braces', 3), ('major', 3), ('river', 3), ('enforcement', 3), ('deaths', 3), ('rises', 3), ('worsens', 3), ('damage', 3), ('hundreds', 3), ('missing', 3), ('torrential', 3), ('deadly', 3), ('died', 3), ('explosions', 3), ('donated', 3), ('donation', 3), ('responders', 3), ('heart', 3), ('rebuilt', 3), ('text', 3), ('homes', 3), ('lives', 3), ('lost', 3), ('toxins', 3), ('survivor', 3), ('financial', 2), ('flooding', 2), ('alive', 2), ('rubble', 2), ('amazing', 2), ('appeal', 2), ('arrest', 2), ('assist', 2), ('attack', 2), ('investigation', 2), ('shot', 2), ('bombings', 2), ('news', 2)]

In [61]:
single_words_df = sorted_df[sorted_df['crisis_names'].str.split().str.len() == 1]# only to detect seingular words

In [63]:
single_words_df.to_csv("../processed/single_crisis_words.csv", index=False)

In [64]:
single_words_df.head(10)

    crisis_names
19      affected
357    aftermath
322       arrest
337       attack
363  authorities
116        blast
160       bomber
92       bombing
51        braces
343       buried

In [65]:
single_words_df.shape

(86, 1)

### singular words
singular words which are extracted from the main crisilexrec datset to trim down the unnecessary words and more over to remove the redudntdant words or redundant menaing words.

In [66]:
scw=pd.read_csv("../processed/single_crisis_words.csv")

In [99]:
remove_words= {
    "braces","aftermath","devastating","people", "praying",
    "video", "saddened", "major", "enforcement", "rises", 
    "worsens", "hundreds", "text", "homes", "lost", "financial",
    "amazing", "appeal", "rubble", "news","displaced","dozens",
    "dramatic", "events", "impacted", "investigation","levy",
    "massive","rebuild","rebuilt","recover", "redcross", "relief",
    "responders", "residents", "stream", "terrifying","unaccounted",
    "volunteers","warning","affected","authorities","donate","disaster",
    "footage","magnitude","cleanup"


}

In [100]:
scw = scw[
    ~scw["crisis_names"].isin(remove_words)
]

In [101]:
scw.shape

(52, 1)

here below we tried to normalize the complex words

In [104]:
scw.to_csv("../processed/trimmed_single_words.csv", index=False)

In [106]:
replace_map ={
    "bomber":"bomb",
    "bombing":"bomb",

    "bushfire":"fire",
    "firefighters":"fire",

    "dead":"death",
    "deadly":"death",

    "floodwaters":"flood",
}

In [108]:


# Load dataset
tsw = pd.read_csv("../processed/trimmed_single_words.csv")

# Column containing words
column = "crisis_names"

# Convert to lowercase
tsw[column] = tsw[column].str.lower()

# Replace words using mapping
tsw[column] = tsw[column].replace(replace_map)

# Remove duplicates
new_df = tsw.drop_duplicates(subset=[column])

# Reset index
new_df = new_df.reset_index(drop=True)

# Print result
print(new_df)

# Save new dataset
new_df.to_csv("../processed/normalized_trimmed_single_words.csv", index=False)

   crisis_names
0        arrest
1        attack
2         blast
3          bomb
4        buried
5          fire
6    casualties
7        crisis
8        damage
9         death
10    destroyed
11  destruction
12    emergency
13    evacuated
14     evacuees
15    explosion
16   fatalities
17        flood
18    hurricane
19     imminent
20      injured
21     injuries
22    inundated
23     landfall
24     military
25      nursing
26      prayers
27      ravaged
28       recede
29       rescue
30     rescuers
31       safety
32      seismic
33      soldier
34        storm
35    surviving
36     survivor
37       terror
38         toll
39      tornado
40   torrential
41       toxins
42      tragedy
43       tragic
44       troops
45      twister
46      victims

In [109]:
ntsw = pd.read_csv("../processed/normalized_trimmed_single_words.csv")
ntsw.shape

(47, 1)

In [36]:
word_map = {}

for sentence in sorted_df["crisis_names"]:

    words = sentence.lower().split()

    for word in words:

        if word not in word_map:
            word_map[word] = []

        word_map[word].append(sentence)

In [37]:
word_map

{'accepting': ['accepting financial'],
 'financial': ['accepting financial', 'financial donations'],
 'affected': ['affected',
  'affected areas',
  'affected explosion',
  'affected flooding',
  'affected hurricane',
  'affected tornado',
  'flood affected',
  'help affected',
  'prayers affected',
  'praying affected'],
 'areas': ['affected areas'],
 'explosion': ['affected explosion',
  'another explosion',
  'dead explosion',
  'deadly explosion',
  'explosion',
  'explosion caught',
  'explosion fertiliser',
  'explosion fire',
  'explosion injured',
  'explosion registered',
  'explosion reported',
  'explosion ripped',
  'explosion victims',
  'explosion video',
  'explosion voted',
  'fertilizer explosion',
  'fire explosion',
  'following explosion',
  'huge explosion',
  'injured explosion',
  'large explosion',
  'major explosion',
  'massive explosion',
  'missing explosion',
  'reported explosion',
  'terrible explosion',
  'victims explosion',
  'video explosion'],
 'flooding': ['affected flooding', 'severe flooding'],
 'hurricane': ['affected hurricane',
  'brought hurricane',
  'coast hurricane',
  'damaged hurricane',
  'dealing hurricane',
  'dying hurricane',
  'effected hurricane',
  'hurricane',
  'hurricane black',
  'hurricane category',
  'hurricane coming',
  'lives hurricane',
  'name hurricane',
  'path hurricane',
  'prepare hurricane',
  'safe hurricane',
  'saying hurricane',
  'terrified hurricane',
  'time hurricane',
  'waiting hurricane',
  'watch hurricane'],
 'tornado': ['affected tornado',
  'city tornado',
  'cross tornado',
  'deadly tornado',
  'devastating tornado',
  'donate tornado',
  'flood tornado',
  'help tornado',
  'massive tornado',
  'tornado',
  'tornado damage',
  'tornado disaster',
  'tornado flood',
  'tornado relief',
  'tornado survivor',
  'tornado victims'],
 'aftermath': ['aftermath'],
 'alive': ['alive rubble', 'buried alive'],
 'rubble': ['alive rubble', 'rubble'],
 'amazing': ['amazing rescue', 'storms amazing'],
 'rescue': ['amazing rescue',
  'daring rescue',
  'rescue',
  'rescue teenager',
  'rescue women'],
 'another': ['another explosion'],
 'appeal': ['appeal launched', 'flood appeal'],
 'launched': ['appeal launched'],
 'arrest': ['arrest', 'breaking arrest'],
 'assist': ['assist people', 'donations assist'],
 'people': ['assist people',
  'killed people',
  'people dead',
  'people died',
  'people injured',
  'people killed',
  'people trapped',
  'police people',
  'prayers people'],
 'attack': ['attack', 'terror attack'],
 'authorities': ['authorities'],
 'blast': ['blast'],
 'bodies': ['bodies recovered'],
 'recovered': ['bodies recovered'],
 'bomber': ['bomber'],
 'bombing': ['bombing',
  'bombing case',
  'bombing investigation',
  'bombing shot',
  'bombing suspect',
  'bombing victims',
  'bombing witnesses',
  'seconds bombing',
  'suspect bombing'],
 'case': ['bombing case'],
 'investigation': ['bombing investigation', 'investigation'],
 'shot': ['bombing shot', 'shot killed'],
 'suspect': ['bombing suspect',
  'breaking suspect',
  'identified suspect',
  'police suspect',
  'suspect bombing',
  'suspect dead',
  'suspect killed',
  'suspect pinned',
  'suspect run'],
 'victims': ['bombing victims',
  'donated victims',
  'explosion victims',
  'flood victims',
  'help victims',
  'prayers victims',
  'praying victims',
  'thoughts victims',
  'tornado victims',
  'victims',
  'victims donate',
  'victims explosion',
  'victims lost',
  'victims waters'],
 'witnesses': ['bombing witnesses'],
 'bombings': ['bombings reports', 'bombings saddened'],
 'reports': ['bombings reports'],
 'saddened': ['bombings saddened', 'saddened', 'saddened loss'],
 'braces': ['braces', 'braces major', 'braces river'],
 'major': ['braces major', 'major explosion', 'major flood'],
 'river': ['braces river', 'high river', 'river peaks'],
 'breaking': ['breaking arrest',
  'breaking enforcement',
  'breaking news',
  'breaking suspect'],
 'enforcement': ['breaking enforcement',
  'enforcement',
  'enforcement official'],
 'news': ['breaking news', 'news flood'],
 'brought': ['brought hurricane'],
 'buried': ['buried', 'buried alive'],
 'bushfire': ['bushfire'],
 'casualties': ['casualties'],
 'city': ['city tornado', 'prayers city'],
 'cleanup': ['cleanup'],
 'climate': ['climate change'],
 'change': ['climate change'],
 'coast': ['coast hurricane'],
 'communities': ['communities damaged', 'rebuilt communities'],
 'damaged': ['communities damaged', 'damaged hurricane'],
 'confirmed': ['confirmed dead', 'deaths confirmed'],
 'dead': ['confirmed dead',
  'dead',
  'dead explosion',
  'dead floods',
  'dead hundreds',
  'dead injured',
  'dead missing',
  'dead torrential',
  'feared dead',
  'people dead',
  'reported dead',
  'reportedly dead',
  'suspect dead'],
 'cost': ['cost deaths', 'flood cost'],
 'deaths': ['cost deaths', 'deaths confirmed', 'peaks deaths'],
 'counts': ['counts flood'],
 'flood': ['counts flood',
  'facing flood',
  'fire flood',
  'flash flood',
  'flood',
  'flood affected',
  'flood alerts',
  'flood appeal',
  'flood claims',
  'flood cost',
  'flood crisis',
  'flood damage',
  'flood death',
  'flood disaster',
  'flood emergency',
  'flood hits',
  'flood homeowners',
  'flood levy',
  'flood peak',
  'flood powerful',
  'flood ravaged',
  'flood recovery',
  'flood relief',
  'flood situation',
  'flood threat',
  'flood toll',
  'flood tornado',
  'flood victims',
  'flood warnings',
  'flood waters',
  'flood worsens',
  'flood years',
  'help flood',
  'hoisted flood',
  'house flood',
  'major flood',
  'missing flood',
  'morning flood',
  'news flood',
  'opposed flood',
  'photos flood',
  'tornado flood',
  'toxins flood',
  'visiting flood'],
 'crisis': ['crisis',
  'crisis deepens',
  'crisis found',
  'crisis rises',
  'crisis unfolds',
  'crisis worsens',
  'flood crisis'],
 'deepens': ['crisis deepens', 'deepens death'],
 'found': ['crisis found'],
 'rises': ['crisis rises', 'toll rises', 'water rises'],
 'unfolds': ['crisis unfolds'],
 'worsens': ['crisis worsens', 'flood worsens', 'worsens eastern'],
 'cross': ['cross tornado', 'donate cross'],
 'damage': ['damage', 'flood damage', 'tornado damage'],
 'daring': ['daring rescue'],
 'floods': ['dead floods',
  'floods force',
  'floods kill',
  'surging floods',
  'teenager floods'],
 'hundreds': ['dead hundreds', 'hundreds homes', 'hundreds injured'],
 'injured': ['dead injured',
  'explosion injured',
  'hundreds injured',
  'injured',
  'injured explosion',
  'killed injured',
  'people injured',
  'reported injured'],
 'missing': ['dead missing', 'missing explosion', 'missing flood'],
 'torrential': ['dead torrential', 'torrential', 'torrential rains'],
 'deadly': ['deadly', 'deadly explosion', 'deadly tornado'],
 'dealing': ['dealing hurricane'],
 'death': ['death', 'death toll', 'deepens death', 'flood death'],
 'toll': ['death toll', 'flood toll', 'toll', 'toll rises'],
 'destroyed': ['destroyed'],
 'destruction': ['destruction'],
 'devastating': ['devastating', 'devastating tornado'],
 'died': ['died explosions', 'girl died', 'people died'],
 'explosions': ['died explosions',
  'explosions running',
  'marathon explosions'],
 'disaster': ['disaster',
  'disaster relief',
  'flood disaster',
  'tornado disaster'],
 'relief': ['disaster relief',
  'flood relief',
  'relief',
  'relief efforts',
  'relief fund',
  'tornado relief'],
 'disasters': ['disasters txting', 'response disasters'],
 'txting': ['disasters txting', 'txting redcross'],
 'displaced': ['displaced'],
 'donate': ['donate',
  'donate cross',
  'donate tornado',
  'redcross donate',
  'retweet donate',
  'victims donate'],
 'donated': ['donated million', 'donated victims', 'gets donated'],
 'million': ['donated million'],
 'donation': ['donation help', 'make donation', 'text donation'],
 'help': ['donation help',
  'help affected',
  'help flood',
  'help rebuilt',
  'help text',
  'help tornado',
  'help victims',
  'hotline help',
  'rescuers help',
  'want help'],
 'donations': ['donations assist', 'financial donations'],
 'dozens': ['dozens'],
 'dramatic': ['dramatic'],
 'dying': ['dying hurricane'],
 'effected': ['effected hurricane'],
 'emergency': ['emergency', 'flood emergency'],
 'official': ['enforcement official'],
 'entire': ['entire crowd'],
 'crowd': ['entire crowd'],
 'evacuated': ['evacuated'],
 'evacuees': ['evacuees'],
 'even': ['even scary'],
 'scary': ['even scary'],
 'events': ['events', 'tragic events'],
 'caught': ['explosion caught'],
 'fertiliser': ['explosion fertiliser'],
 'fire': ['explosion fire',
  'fire explosion',
  'fire fighters',
  'fire flood',
  'lurches fire'],
 'registered': ['explosion registered', 'registered magnitude'],
 'reported': ['explosion reported',
  'injuries reported',
  'reported dead',
  'reported explosion',
  'reported injured'],
 'ripped': ['explosion ripped'],
 'video': ['explosion video',
  'shocking video',
  'video capturing',
  'video explosion'],
 'voted': ['explosion voted'],
 'running': ['explosions running', 'risk running'],
 'facing': ['facing flood'],
 'fatalities': ['fatalities'],
 'feared': ['feared dead'],
 'fertilizer': ['fertilizer explosion'],
 'fighters': ['fire fighters'],
 'firefighters': ['firefighters', 'firefighters police'],
 'police': ['firefighters police',
  'killed police',
  'police officer',
  'police people',
  'police suspect'],
 'first': ['first responders'],
 'responders': ['first responders', 'responders', 'responders killed'],
 'flash': ['flash flood'],
 'alerts': ['flood alerts'],
 'claims': ['flood claims'],
 'hits': ['flood hits'],
 'homeowners': ['flood homeowners', 'homeowners reconnect'],
 'levy': ['flood levy', 'levy'],
 'peak': ['flood peak'],
 'powerful': ['flood powerful', 'powerful storms'],
 'ravaged': ['flood ravaged', 'ravaged'],
 'recovery': ['flood recovery'],
 'situation': ['flood situation'],
 'threat': ['flood threat'],
 'warnings': ['flood warnings'],
 'waters': ['flood waters',
  'supplies waters',
  'victims waters',
  'waters recede'],
 'years': ['flood years'],
 'force': ['floods force'],
 'kill': ['floods kill'],
 'floodwaters': ['floodwaters'],
 'following': ['following explosion'],
 'footage': ['footage'],
 'free': ['free hotline'],
 'hotline': ['free hotline', 'hotline help'],
 'gets': ['gets donated'],
 'girl': ['girl died'],
 'give': ['give online', 'redcross give'],
 'online': ['give online'],
 'government': ['government negligent'],
 'negligent': ['government negligent'],
 'heart': ['heart prayers', 'heart praying', 'life heart'],
 'prayers': ['heart prayers',
  'love prayers',
  'prayers',
  'prayers affected',
  'prayers city',
  'prayers families',
  'prayers involved',
  'prayers people',
  'prayers tonight',
  'prayers victims',
  'send prayers',
  'thoughts prayers'],
 'praying': ['heart praying',
  'join praying',
  'praying',
  'praying affected',
  'praying community',
  'praying families',
  'praying victims'],
 'rebuilt': ['help rebuilt', 'rebuilt', 'rebuilt communities'],
 'text': ['help text', 'text donation', 'text redcross'],
 'high': ['high river'],
 'hoisted': ['hoisted flood'],
 'reconnect': ['homeowners reconnect', 'reconnect power'],
 'homes': ['homes inundated', 'hundreds homes', 'thousands homes'],
 'inundated': ['homes inundated', 'inundated'],
 'house': ['house flood'],
 'huge': ['huge explosion'],
 'black': ['hurricane black'],
 'category': ['hurricane category'],
 'coming': ['hurricane coming'],
 'identified': ['identified suspect'],
 'imminent': ['imminent'],
 'impacted': ['impacted'],
 'injuries': ['injuries', 'injuries reported'],
 'join': ['join praying', 'please join'],
 'killed': ['killed injured',
  'killed people',
  'killed police',
  'people killed',
  'responders killed',
  'shot killed',
  'suspect killed'],
 'kills': ['kills forces'],
 'forces': ['kills forces'],
 'landfall': ['landfall'],
 'large': ['large explosion'],
 'leave': ['leave town'],
 'town': ['leave town'],
 'life': ['life heart', 'loss life'],
 'live': ['live coverage'],
 'coverage': ['live coverage'],
 'lives': ['lives hurricane', 'lost lives', 'remember lives'],
 'loss': ['loss life', 'saddened loss'],
 'lost': ['lost legs', 'lost lives', 'victims lost'],
 'legs': ['lost legs'],
 'love': ['love prayers'],
 'lurches': ['lurches fire'],
 'magnitude': ['magnitude', 'registered magnitude'],
 'make': ['make donation'],
 'marathon': ['marathon explosions'],
 'massive': ['massive',
  'massive explosion',
  'massive manhunt',
  'massive tornado',
  'run massive'],
 'manhunt': ['massive manhunt'],
 'medical': ['medical examiner', 'medical office'],
 'examiner': ['medical examiner'],
 'office': ['medical office'],
 'memorial': ['memorial service'],
 'service': ['memorial service'],
 'military': ['military'],
 'morning': ['morning flood'],
 'name': ['name hurricane'],
 'names': ['names terrified'],
 'terrified': ['names terrified', 'terrified hurricane'],
 'need': ['need terrifying'],
 'terrifying': ['need terrifying', 'terrifying'],
 'nursing': ['nursing'],
 'opposed': ['opposed flood'],
 'path': ['path hurricane'],
 'peaks': ['peaks deaths', 'river peaks'],
 'trapped': ['people trapped'],
 'photos': ['photos flood', 'releases photos'],
 'please': ['please join', 'please stay'],
 'stay': ['please stay', 'stay strong'],
 'officer': ['police officer'],
 'power': ['power supplies', 'reconnect power'],
 'supplies': ['power supplies', 'supplies waters'],
 'storms': ['powerful storms', 'storms amazing'],
 'families': ['prayers families', 'praying families'],
 'involved': ['prayers involved'],
 'tonight': ['prayers tonight'],
 'community': ['praying community'],
 'prepare': ['prepare hurricane'],
 'public': ['public safety'],
 'safety': ['public safety', 'safety'],
 'rains': ['rains severely', 'torrential rains'],
 'severely': ['rains severely'],
 'rebuild': ['rebuild'],
 'recede': ['recede', 'waters recede'],
 'recover': ['recover'],
 'redcross': ['redcross',
  'redcross donate',
  'redcross give',
  'text redcross',
  'txting redcross'],
 'reels': ['reels surging'],
 'surging': ['reels surging', 'surging floods'],
 'release': ['release toxins'],
 'toxins': ['release toxins', 'toxins', 'toxins flood'],
 'releases': ['releases images', 'releases photos'],
 'images': ['releases images'],
 'efforts': ['relief efforts'],
 'fund': ['relief fund'],
 'remember': ['remember lives'],
 'reportedly': ['reportedly dead'],
 'teenager': ['rescue teenager', 'teenager floods'],
 'women': ['rescue women'],
 'rescuers': ['rescuers', 'rescuers help'],
 'residents': ['residents'],
 'response': ['response disasters'],
 'return': ['return home'],
 'home': ['return home'],
 'retweet': ['retweet donate'],
 'risk': ['risk running'],
 'run': ['run massive', 'suspect run'],
 'safe': ['safe hurricane'],
 'saying': ['saying hurricane'],
 'seconds': ['seconds bombing'],
 'seismic': ['seismic'],
 'send': ['send prayers'],
 'severe': ['severe flooding'],
 'shocking': ['shocking video'],
 'soldier': ['soldier', 'unknown soldier'],
 'someone': ['someone captured'],
 'captured': ['someone captured'],
 'strong': ['stay strong'],
 'storm': ['storm'],
 'stream': ['stream'],
 'surviving': ['surviving'],
 'survivor': ['survivor', 'survivor finds', 'tornado survivor'],
 'finds': ['survivor finds'],
 'pinned': ['suspect pinned'],
 'terrible': ['terrible explosion'],
 'terror': ['terror', 'terror attack'],
 'thoughts': ['thoughts prayers', 'thoughts victims'],
 'thousands': ['thousands homes'],
 'time': ['time hurricane'],
 'tragedy': ['tragedy'],
 'tragic': ['tragic', 'tragic events'],
 'troops': ['troops', 'troops lend'],
 'lend': ['troops lend'],
 'twister': ['twister'],
 'unaccounted': ['unaccounted'],
 'unknown': ['unknown number', 'unknown soldier'],
 'number': ['unknown number'],
 'capturing': ['video capturing'],
 'visiting': ['visiting flood'],
 'volunteers': ['volunteers'],
 'waiting': ['waiting hurricane'],
 'want': ['want help'],
 'warning': ['warning'],
 'watch': ['watch hurricane'],
 'water': ['water rises'],
 'eastern': ['worsens eastern']}